# # zookeeper service

# zookeeper:
#   image: zookeeper:3.8.0

#   restart: always

#   ports:
#     - '2181:2181'

#   environment:
#     ZOOKEEPER_CLIENT_PORT: 2181

#   networks:
#     - mynetwork

# # kafka service

# kafka:
#   image: confluentinc/cp-kafka:7.3.0

#   restart: always

#   depends_on:
#     - zookeeper

#   ports:
#     - '9092:9092'

#     - '29092:29092'

#   environment:
#     KAFKA_BROKER_ID: 1

#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT

#     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092

#     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

#     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#   networks:
#     - mynetwork

# # kafdrop service

# kafdrop:
#   image: obsidiandynamics/kafdrop:3.30.0

#   restart: always

#   depends_on:
#     - kafka

#   ports:
#     - '9000:9000'

#   environment:
#     KAFKA_BROKERCONNECT: kafka:29092

#     JVM_OPTS: '-Xms32M -Xmx64M'

#     SERVER_SERVLET_CONTEXTPATH: '/'

#   networks:
#     - mynetwork

# # Service NestJS

# nestjs-app:
#   build: .

#   container_name: nestjs

#   restart: always

#   ports:
#     - '3000:3000'

#   depends_on:
#     - postgres-app

#   volumes:
#     - .:/app

#   command: ['npm', 'run', 'start:dev']

#   DATABASE_URL: postgresql://postgres:123@postgres-app:5432/nestDB

#   networks:
#     - mynetwork

# networks:
#   mynetwork:

# volumes:
#   postgres-data:
version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=
    depends_on:
      - zookeeper
